{{- if .Values.approval.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cha.fullname" . }}-approval-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cha.labels" . | nindent 4 }}
    cha.bionicaisolutions.com/role: approval-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8443
      targetPort: http
      protocol: TCP
  selector:
    {{- include "cha.selectorLabels" . | nindent 4 }}
    cha.bionicaisolutions.com/role: approval-server
{{- end }}
