// Copyright 2026 Cluster Health Autopilot contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hand for v1alpha1 — Phase 1 of the operator
// port deliberately avoids the codegen toolchain in CI. When Phase 2
// adds controller-runtime, this file is regenerated by
// `controller-gen object` and the hand-written body is replaced.
//
// Keep the function signatures exactly as the codegen produces them
// so the replacement is a no-op diff.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// --- ClusterHealthAutopilot ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *ClusterHealthAutopilot) DeepCopyInto(out *ClusterHealthAutopilot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterHealthAutopilot) DeepCopy() *ClusterHealthAutopilot {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthAutopilot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *ClusterHealthAutopilot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- ClusterHealthAutopilotList ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *ClusterHealthAutopilotList) DeepCopyInto(out *ClusterHealthAutopilotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ClusterHealthAutopilot, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterHealthAutopilotList) DeepCopy() *ClusterHealthAutopilotList {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthAutopilotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *ClusterHealthAutopilotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- ClusterHealthAutopilotSpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *ClusterHealthAutopilotSpec) DeepCopyInto(out *ClusterHealthAutopilotSpec) {
	*out = *in
	in.Image.DeepCopyInto(&out.Image)
	if in.Watcher != nil {
		out.Watcher = new(WatcherSpec)
		*out.Watcher = *in.Watcher
	}
	if in.Diagnose != nil {
		out.Diagnose = new(DiagnoseSpec)
		*out.Diagnose = *in.Diagnose
	}
	if in.Remediate != nil {
		out.Remediate = new(RemediateSpec)
		*out.Remediate = *in.Remediate
	}
	if in.Alerting != nil {
		out.Alerting = new(AlertingSpec)
		in.Alerting.DeepCopyInto(out.Alerting)
	}
	if in.AI != nil {
		out.AI = new(AISpec)
		in.AI.DeepCopyInto(out.AI)
	}
	if in.Approval != nil {
		out.Approval = new(ApprovalSpec)
		in.Approval.DeepCopyInto(out.Approval)
	}
	if in.ExternalDNS != nil {
		out.ExternalDNS = new(ExternalDNSSpec)
		in.ExternalDNS.DeepCopyInto(out.ExternalDNS)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterHealthAutopilotSpec) DeepCopy() *ClusterHealthAutopilotSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthAutopilotSpec)
	in.DeepCopyInto(out)
	return out
}

// --- ClusterHealthAutopilotStatus ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *ClusterHealthAutopilotStatus) DeepCopyInto(out *ClusterHealthAutopilotStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterHealthAutopilotStatus) DeepCopy() *ClusterHealthAutopilotStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthAutopilotStatus)
	in.DeepCopyInto(out)
	return out
}

// --- ImageSpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		out.PullSecrets = append([]string(nil), in.PullSecrets...)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// --- AlertingSpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AlertingSpec) DeepCopyInto(out *AlertingSpec) {
	*out = *in
	if in.Slack != nil {
		out.Slack = new(SlackSpec)
		in.Slack.DeepCopyInto(out.Slack)
	}
	if in.Alertmanager != nil {
		out.Alertmanager = new(AlertmanagerSpec)
		*out.Alertmanager = *in.Alertmanager
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *AlertingSpec) DeepCopy() *AlertingSpec {
	if in == nil {
		return nil
	}
	out := new(AlertingSpec)
	in.DeepCopyInto(out)
	return out
}

// --- SlackSpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SlackSpec) DeepCopyInto(out *SlackSpec) {
	*out = *in
	if in.Alerts != nil {
		out.Alerts = new(SlackChannelSpec)
		*out.Alerts = *in.Alerts
	}
	if in.Critical != nil {
		out.Critical = new(SlackChannelSpec)
		*out.Critical = *in.Critical
	}
	if in.HealthInfo != nil {
		out.HealthInfo = new(SlackChannelSpec)
		*out.HealthInfo = *in.HealthInfo
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *SlackSpec) DeepCopy() *SlackSpec {
	if in == nil {
		return nil
	}
	out := new(SlackSpec)
	in.DeepCopyInto(out)
	return out
}

// --- AISpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AISpec) DeepCopyInto(out *AISpec) {
	*out = *in
	if in.Image != nil {
		out.Image = new(ImageSpec)
		in.Image.DeepCopyInto(out.Image)
	}
	if in.APIKey != nil {
		out.APIKey = new(AIAPIKeySpec)
		*out.APIKey = *in.APIKey
	}
	if in.T3 != nil {
		out.T3 = new(AIT3Spec)
		in.T3.DeepCopyInto(out.T3)
	}
	if in.Memory != nil {
		out.Memory = new(AIMemorySpec)
		in.Memory.DeepCopyInto(out.Memory)
	}
	if in.ExtraArgs != nil {
		out.ExtraArgs = make([]string, len(in.ExtraArgs))
		copy(out.ExtraArgs, in.ExtraArgs)
	}
	if in.ExtraEnv != nil {
		out.ExtraEnv = make([]AIExtraEnv, len(in.ExtraEnv))
		for i := range in.ExtraEnv {
			in.ExtraEnv[i].DeepCopyInto(&out.ExtraEnv[i])
		}
	}
}

// DeepCopyInto for AIExtraEnv.
func (in *AIExtraEnv) DeepCopyInto(out *AIExtraEnv) {
	*out = *in
	if in.ValueFrom != nil {
		out.ValueFrom = new(AIExtraEnvSource)
		if in.ValueFrom.SecretKeyRef != nil {
			out.ValueFrom.SecretKeyRef = new(AIExtraEnvSecretKeyRef)
			*out.ValueFrom.SecretKeyRef = *in.ValueFrom.SecretKeyRef
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *AIExtraEnv) DeepCopy() *AIExtraEnv {
	if in == nil {
		return nil
	}
	out := new(AIExtraEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy returns a deep copy of the receiver.
func (in *AISpec) DeepCopy() *AISpec {
	if in == nil {
		return nil
	}
	out := new(AISpec)
	in.DeepCopyInto(out)
	return out
}

// --- AIT3Spec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIT3Spec) DeepCopyInto(out *AIT3Spec) {
	*out = *in
	if in.VaultAllowedPrefixes != nil {
		out.VaultAllowedPrefixes = make([]string, len(in.VaultAllowedPrefixes))
		copy(out.VaultAllowedPrefixes, in.VaultAllowedPrefixes)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *AIT3Spec) DeepCopy() *AIT3Spec {
	if in == nil {
		return nil
	}
	out := new(AIT3Spec)
	in.DeepCopyInto(out)
	return out
}

// --- AIMemorySpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIMemorySpec) DeepCopyInto(out *AIMemorySpec) {
	*out = *in
	if in.Image != nil {
		out.Image = new(ImageSpec)
		in.Image.DeepCopyInto(out.Image)
	}
	if in.Storage != nil {
		out.Storage = new(AIMemoryStorageSpec)
		*out.Storage = *in.Storage
	}
	if in.Embeddings != nil {
		out.Embeddings = new(AIEmbeddingsSpec)
		*out.Embeddings = *in.Embeddings
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *AIMemorySpec) DeepCopy() *AIMemorySpec {
	if in == nil {
		return nil
	}
	out := new(AIMemorySpec)
	in.DeepCopyInto(out)
	return out
}

// --- ApprovalSpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *ApprovalSpec) DeepCopyInto(out *ApprovalSpec) {
	*out = *in
	if in.Image != nil {
		out.Image = new(ImageSpec)
		in.Image.DeepCopyInto(out.Image)
	}
	if in.SigningKey != nil {
		out.SigningKey = new(ApprovalSigningKeySpec)
		*out.SigningKey = *in.SigningKey
	}
	if in.Store != nil {
		out.Store = new(ApprovalStoreSpec)
		*out.Store = *in.Store
	}
	if in.Ingress != nil {
		out.Ingress = new(ApprovalIngressSpec)
		in.Ingress.DeepCopyInto(out.Ingress)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ApprovalSpec) DeepCopy() *ApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(ApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// --- ApprovalIngressSpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *ApprovalIngressSpec) DeepCopyInto(out *ApprovalIngressSpec) {
	*out = *in
	if in.Annotations != nil {
		out.Annotations = make(map[string]string, len(in.Annotations))
		for k, v := range in.Annotations {
			out.Annotations[k] = v
		}
	}
	if in.TLS != nil {
		out.TLS = new(ApprovalIngressTLSSpec)
		*out.TLS = *in.TLS
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ApprovalIngressSpec) DeepCopy() *ApprovalIngressSpec {
	if in == nil {
		return nil
	}
	out := new(ApprovalIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// --- ExternalDNSSpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *ExternalDNSSpec) DeepCopyInto(out *ExternalDNSSpec) {
	*out = *in
	if in.Cloudflare != nil {
		out.Cloudflare = new(CloudflareSpec)
		in.Cloudflare.DeepCopyInto(out.Cloudflare)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ExternalDNSSpec) DeepCopy() *ExternalDNSSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// --- CloudflareSpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *CloudflareSpec) DeepCopyInto(out *CloudflareSpec) {
	*out = *in
	if in.APITokenSecretRef != nil {
		out.APITokenSecretRef = new(CloudflareSecretRef)
		*out.APITokenSecretRef = *in.APITokenSecretRef
	}
	if in.ZoneIDs != nil {
		out.ZoneIDs = make([]string, len(in.ZoneIDs))
		copy(out.ZoneIDs, in.ZoneIDs)
	}
	if in.ExpectedTargets != nil {
		out.ExpectedTargets = make([]string, len(in.ExpectedTargets))
		copy(out.ExpectedTargets, in.ExpectedTargets)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *CloudflareSpec) DeepCopy() *CloudflareSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareSpec)
	in.DeepCopyInto(out)
	return out
}

// Note: CloudflareSecretRef contains only string fields; value-copy
// in CloudflareSpec.DeepCopyInto is sufficient — no separate
// DeepCopyInto/DeepCopy needed.

// --- Silence ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *Silence) DeepCopyInto(out *Silence) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *Silence) DeepCopy() *Silence {
	if in == nil {
		return nil
	}
	out := new(Silence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *Silence) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- SilenceList ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SilenceList) DeepCopyInto(out *SilenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Silence, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *SilenceList) DeepCopy() *SilenceList {
	if in == nil {
		return nil
	}
	out := new(SilenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *SilenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- SilenceSpec ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SilenceSpec) DeepCopyInto(out *SilenceSpec) {
	*out = *in
	out.Matcher = in.Matcher
	in.Until.DeepCopyInto(&out.Until)
}

// DeepCopy returns a deep copy of the receiver.
func (in *SilenceSpec) DeepCopy() *SilenceSpec {
	if in == nil {
		return nil
	}
	out := new(SilenceSpec)
	in.DeepCopyInto(out)
	return out
}

// --- SilenceStatus ---

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SilenceStatus) DeepCopyInto(out *SilenceStatus) {
	*out = *in
	if in.LastMatchAt != nil {
		out.LastMatchAt = new(metav1.Time)
		in.LastMatchAt.DeepCopyInto(out.LastMatchAt)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *SilenceStatus) DeepCopy() *SilenceStatus {
	if in == nil {
		return nil
	}
	out := new(SilenceStatus)
	in.DeepCopyInto(out)
	return out
}
